SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
UPDATE `policy` SET `total_hire_client`=2 WHERE `id`=1;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=2;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=3;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=4;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=7;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=8;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=9;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=11;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=13;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=14;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=16;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=17;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=53;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=141;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=159;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=279;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=280;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=447;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=518;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=1306;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=1307;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=1455;
UPDATE `policy` SET `total_hire_client`=7 WHERE `id`=1829;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=2373;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=2420;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=2505;
UPDATE `policy` SET `total_hire_client`=1 WHERE `id`=2700;
COMMIT;